from __future__ import annotations

import hashlib
import http.client
import json
import math
import re
import socket
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from .graphify_embedding_handoff import (
    DEFAULT_GRAPHIFY_EMBEDDING_DERIVED_ROOT,
    _is_relative_to,
    _require_not_live,
    _safe_derived_root,
)
from .guardrails import GuardrailError, is_protected_relative, write_json
from .indexing_wrapper import normalize_loopback_ollama_base_url
from .resource_preflight import collect_resource_preflight

TOKEN_RE = re.compile(r"[\w\-]+", re.UNICODE)
DEFAULT_HASHING_DIMENSIONS = 128
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "bge-m3"
ALLOWED_OLLAMA_MODELS = {"bge-m3", "bge-m3:latest"}
DEFAULT_MAX_FILES_PER_RUN = 50
MAX_FILES_PER_RUN_HARD_CAP = 75
DEFAULT_MAX_CHARS_PER_FILE = 80_000
DEFAULT_MAX_CHARS_PER_CHUNK = 2_000
DEFAULT_CHUNK_OVERLAP = 200
DEFAULT_OLLAMA_TIMEOUT_SECONDS = 180


@dataclass(frozen=True)
class EmbeddedFileRecord:
    path: str
    hash: str
    status: str
    embedding_file: str | None
    dimensions: int
    token_count: int
    chunk_count: int = 0
    skipped_reason: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class GraphifyEmbeddingRunReport:
    mode: str
    manifest: str
    derived_root: str
    provider: str
    dimensions: int
    processed: int
    skipped: int
    records: list[EmbeddedFileRecord]
    safety: dict[str, bool]
    resource_preflight: dict[str, Any] | None = None
    ollama_unloaded_after_run: bool | None = None

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["records"] = [item.to_dict() for item in self.records]
        return data


def _load_manifest(path: str | Path) -> dict[str, Any]:
    manifest = _require_not_live(path)
    if manifest.name != "embedding-manifest.json" or not manifest.is_file():
        raise GuardrailError(f"Expected Graphify embedding-manifest.json: {manifest}")
    allowed_root = Path(__file__).resolve().parents[2] / "out" / "reports" / "graphify-embedding-handoff"
    if not _is_relative_to(manifest, allowed_root.resolve()):
        raise GuardrailError(f"Manifest must be generated by graphify_embedding_handoff under {allowed_root}")
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    if payload.get("mode") != "graphify-derived-embedding-manifest":
        raise GuardrailError("Manifest is not graphify-derived")
    _validate_embedding_policy(payload.get("embedding_policy"))
    return payload


def _validate_embedding_policy(policy: Any) -> None:
    if not isinstance(policy, dict):
        raise GuardrailError("Manifest is missing embedding_policy")
    required = {
        "auto_execute": False,
        "concurrency": 1,
        "derived_cache_only": True,
        "checkpoint_resume_required": True,
    }
    for key, expected in required.items():
        if policy.get(key) != expected:
            raise GuardrailError(f"Manifest embedding_policy.{key} must be {expected!r}")
    provider_policy = policy.get("provider")
    if provider_policy not in {"local_only_or_explicitly_approved", "local_only"}:
        raise GuardrailError("Manifest embedding_policy.provider must require local-only embeddings")


def _safe_sandbox_from_manifest(payload: dict[str, Any]) -> Path:
    sandbox_raw = payload.get("sandbox_vault")
    if not isinstance(sandbox_raw, str):
        raise GuardrailError("Manifest is missing sandbox_vault")
    sandbox = _require_not_live(sandbox_raw)
    sandbox_root = Path(__file__).resolve().parents[2] / "out" / "sandbox-vaults"
    if sandbox == sandbox_root.resolve():
        raise GuardrailError("Manifest sandbox_vault must be a named sandbox, not the sandbox root")
    if not sandbox.is_dir() or not _is_relative_to(sandbox, sandbox_root.resolve()):
        raise GuardrailError(f"Manifest sandbox_vault must be an existing sandbox under {sandbox_root}: {sandbox}")
    return sandbox


def _candidate_path(sandbox: Path, rel: str) -> Path:
    candidate = Path(rel)
    if candidate.is_absolute() or ".." in candidate.parts or is_protected_relative(candidate.as_posix()):
        raise GuardrailError(f"Unsafe manifest candidate path: {rel}")
    target = (sandbox / candidate).resolve()
    if not _is_relative_to(target, sandbox):
        raise GuardrailError(f"Candidate escapes sandbox: {rel}")
    if not target.is_file():
        raise GuardrailError(f"Manifest candidate is missing from sandbox: {rel}")
    return target


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _tokens(text: str) -> list[str]:
    return [match.group(0).lower() for match in TOKEN_RE.finditer(text)]


def _hashing_embedding(text: str, *, dimensions: int = DEFAULT_HASHING_DIMENSIONS) -> tuple[list[float], int]:
    if dimensions < 8 or dimensions > 4096:
        raise GuardrailError("hashing dimensions must be between 8 and 4096")
    vector = [0.0] * dimensions
    tokens = _tokens(text)
    for token in tokens:
        digest = hashlib.blake2b(token.encode("utf-8"), digest_size=8).digest()
        value = int.from_bytes(digest, "big")
        index = value % dimensions
        sign = 1.0 if (value >> 63) == 0 else -1.0
        vector[index] += sign
    norm = math.sqrt(sum(value * value for value in vector))
    if norm:
        vector = [round(value / norm, 8) for value in vector]
    return vector, len(tokens)



def _ollama_embed(
    text: str,
    *,
    base_url: str = DEFAULT_OLLAMA_BASE_URL,
    model: str = DEFAULT_OLLAMA_MODEL,
    timeout_seconds: int = 60,
    keep_alive: str | int | None = None,
) -> tuple[list[float], int]:
    normalized = normalize_loopback_ollama_base_url(base_url)
    if not model or any(ch.isspace() for ch in model):
        raise GuardrailError(f"Invalid Ollama embedding model: {model!r}")
    if model not in ALLOWED_OLLAMA_MODELS:
        raise GuardrailError(f"Ollama embedding model must be bge-m3 for this runner: {model!r}")
    payload_dict: dict[str, Any] = {"model": model, "input": text}
    if keep_alive is not None:
        payload_dict["keep_alive"] = keep_alive
    payload = json.dumps(payload_dict).encode("utf-8")
    request = urllib.request.Request(
        urllib.parse.urljoin(normalized + "/", "api/embed"),
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
            data = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")[:500]
        detail = f"HTTP {exc.code}" + (f": {body}" if body else "")
        raise GuardrailError(f"Local Ollama embedding request failed: {detail}") from exc
    except (urllib.error.URLError, TimeoutError, socket.timeout, http.client.RemoteDisconnected, json.JSONDecodeError) as exc:
        raise GuardrailError(f"Local Ollama embedding request failed: {exc}") from exc
    embeddings = data.get("embeddings")
    if not isinstance(embeddings, list) or not embeddings or not isinstance(embeddings[0], list):
        raise GuardrailError("Ollama /api/embed response did not include embeddings")
    vector = [float(value) for value in embeddings[0]]
    token_count = len(_tokens(text))
    return vector, token_count



def _ollama_unload(
    *,
    base_url: str = DEFAULT_OLLAMA_BASE_URL,
    model: str = DEFAULT_OLLAMA_MODEL,
    timeout_seconds: int = 30,
) -> bool:
    """Ask local Ollama to unload the embedding model after a bounded run.

    Ollama keeps models resident for fast follow-up requests. On this small VPS
    bge-m3 is CPU-only/F16 and uses about 1.1 GiB RSS, so graphify embedding
    runs should release it when the batch completes.
    """
    try:
        _ollama_embed(
            " ",
            base_url=base_url,
            model=model,
            timeout_seconds=timeout_seconds,
            keep_alive=0,
        )
    except GuardrailError:
        return False
    return True

def _chunk_text(text: str, *, max_chars: int, overlap: int) -> list[str]:
    if max_chars < 200 or max_chars > 20_000:
        raise GuardrailError("max_chars_per_chunk must be between 200 and 20000")
    if overlap < 0 or overlap >= max_chars // 2:
        raise GuardrailError("chunk_overlap must be >= 0 and smaller than half max_chars_per_chunk")
    if not text:
        return [""]
    chunks: list[str] = []
    start = 0
    previous_start = -1
    while start < len(text):
        if start <= previous_start:
            raise GuardrailError("chunking failed to make forward progress")
        previous_start = start
        hard_end = min(len(text), start + max_chars)
        end = hard_end
        if hard_end < len(text):
            newline = text.rfind("\n\n", start, hard_end)
            if newline > start + max_chars // 2:
                end = newline + 2
            else:
                space = text.rfind(" ", start, hard_end)
                if space > start + max_chars // 2:
                    end = space + 1
        if end <= start:
            end = hard_end
        chunk = text[start:end].strip()
        if chunk:
            chunks.append(chunk)
        if end >= len(text):
            break
        start = max(previous_start + 1, end - overlap)
    return chunks or [text[:max_chars]]

def _embed_chunk_adaptive(
    chunk: str,
    *,
    provider: str,
    dimensions: int,
    ollama_base_url: str,
    ollama_model: str,
    ollama_timeout_seconds: int = DEFAULT_OLLAMA_TIMEOUT_SECONDS,
    min_chars: int = 500,
) -> list[tuple[str, list[float], int]]:
    """Embed a chunk, splitting on Ollama size/time failures.

    The runner can start with larger Graphify-derived chunks for better semantic
    context, but local Ollama on CPU may reject or time out on oversized inputs.
    This helper preserves fail-closed behavior while degrading to smaller chunks
    inside the same bounded file/manifest scope.
    """
    if provider == "local-hashing-v1":
        vector, token_count = _hashing_embedding(chunk, dimensions=dimensions)
        return [(chunk, vector, token_count)]
    if provider != "ollama":
        raise GuardrailError(f"Unsupported embedding provider: {provider}")
    try:
        vector, token_count = _ollama_embed(
            chunk,
            base_url=ollama_base_url,
            model=ollama_model,
            timeout_seconds=ollama_timeout_seconds,
        )
        return [(chunk, vector, token_count)]
    except GuardrailError as exc:
        if len(chunk) <= min_chars:
            raise
        midpoint = len(chunk) // 2
        split_at = max(chunk.rfind("\n\n", 0, midpoint), chunk.rfind(" ", 0, midpoint))
        if split_at < max(1, min_chars // 2):
            split_at = midpoint
        left = chunk[:split_at].strip()
        right = chunk[split_at:].strip()
        if not left or not right:
            raise GuardrailError(f"Local Ollama embedding request failed and chunk could not be split safely: {exc}") from exc
        return _embed_chunk_adaptive(
            left,
            provider=provider,
            dimensions=dimensions,
            ollama_base_url=ollama_base_url,
            ollama_model=ollama_model,
            ollama_timeout_seconds=ollama_timeout_seconds,
            min_chars=min_chars,
        ) + _embed_chunk_adaptive(
            right,
            provider=provider,
            dimensions=dimensions,
            ollama_base_url=ollama_base_url,
            ollama_model=ollama_model,
            ollama_timeout_seconds=ollama_timeout_seconds,
            min_chars=min_chars,
        )


def _embedding_output_path(derived_root: Path, rel_path: str) -> Path:
    digest = hashlib.sha256(rel_path.encode("utf-8")).hexdigest()[:16]
    return derived_root / "embeddings" / f"{digest}.json"


def _existing_embedding_record(
    *,
    out_path: Path,
    rel_path: str,
    expected_hash: str,
    provider: str,
    ollama_base_url: str,
    ollama_model: str,
    max_chars_per_chunk: int,
    chunk_overlap: int,
) -> EmbeddedFileRecord | None:
    if not out_path.is_file():
        return None
    try:
        payload = json.loads(out_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if payload.get("path") != rel_path or payload.get("hash") != expected_hash or payload.get("provider") != provider:
        return None
    if payload.get("max_chars_per_chunk") != max_chars_per_chunk or payload.get("chunk_overlap") != chunk_overlap:
        return None
    if provider == "ollama":
        if payload.get("model") != ollama_model or payload.get("ollama_base_url") != ollama_base_url:
            return None
    return EmbeddedFileRecord(
        path=rel_path,
        hash=expected_hash,
        status="embedded",
        embedding_file=str(out_path),
        dimensions=int(payload.get("dimensions") or 0),
        token_count=int(payload.get("token_count") or 0),
        chunk_count=int(payload.get("chunk_count") or 0),
    )


def _write_embedding_record(
    *,
    target_file: Path,
    rel_path: str,
    expected_hash: str,
    derived_root: Path,
    dimensions: int,
    max_chars_per_file: int,
    max_chars_per_chunk: int,
    chunk_overlap: int,
    provider: str,
    ollama_base_url: str = DEFAULT_OLLAMA_BASE_URL,
    ollama_model: str = DEFAULT_OLLAMA_MODEL,
    ollama_timeout_seconds: int = DEFAULT_OLLAMA_TIMEOUT_SECONDS,
) -> EmbeddedFileRecord:
    actual_hash = _sha256(target_file)
    if actual_hash != expected_hash:
        return EmbeddedFileRecord(
            path=rel_path,
            hash=actual_hash,
            status="skipped",
            embedding_file=None,
            dimensions=dimensions,
            token_count=0,
            chunk_count=0,
            skipped_reason="hash_mismatch_manifest_stale",
        )
    out_path = _embedding_output_path(derived_root, rel_path)
    existing = _existing_embedding_record(
        out_path=out_path,
        rel_path=rel_path,
        expected_hash=expected_hash,
        provider=provider,
        ollama_base_url=ollama_base_url,
        ollama_model=ollama_model,
        max_chars_per_chunk=max_chars_per_chunk,
        chunk_overlap=chunk_overlap,
    )
    if existing is not None:
        return existing
    full_text = target_file.read_text(encoding="utf-8", errors="replace")
    original_char_count = len(full_text)
    text = full_text[:max_chars_per_file]
    truncated = original_char_count > len(text)
    if not text.strip():
        return EmbeddedFileRecord(
            path=rel_path,
            hash=actual_hash,
            status="skipped",
            embedding_file=None,
            dimensions=dimensions,
            token_count=0,
            chunk_count=0,
            skipped_reason="empty_text_after_truncation",
        )
    chunks = _chunk_text(text, max_chars=max_chars_per_chunk, overlap=chunk_overlap)
    chunk_records: list[dict[str, Any]] = []
    actual_dimensions = dimensions
    total_tokens = 0
    chunk_index = 0
    for chunk in chunks:
        embedded_parts = _embed_chunk_adaptive(
            chunk,
            provider=provider,
            dimensions=dimensions,
            ollama_base_url=ollama_base_url,
            ollama_model=ollama_model,
            ollama_timeout_seconds=ollama_timeout_seconds,
        )
        for embedded_text, vector, token_count in embedded_parts:
            actual_dimensions = len(vector) if provider == "ollama" else dimensions
            total_tokens += token_count
            chunk_records.append(
                {
                    "chunk_index": chunk_index,
                    "char_count": len(embedded_text),
                    "token_count": token_count,
                    "vector": vector,
                }
            )
            chunk_index += 1
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_json(
        out_path,
        {
            "path": rel_path,
            "hash": actual_hash,
            "provider": provider,
            "model": ollama_model if provider == "ollama" else None,
            "ollama_base_url": ollama_base_url if provider == "ollama" else None,
            "dimensions": actual_dimensions,
            "chunk_count": len(chunk_records),
            "original_char_count": original_char_count,
            "embedded_char_count": len(text),
            "truncated": truncated,
            "max_chars_per_chunk": max_chars_per_chunk,
            "chunk_overlap": chunk_overlap,
            "token_count": total_tokens,
            "chunks": chunk_records,
        },
    )
    return EmbeddedFileRecord(
        path=rel_path,
        hash=actual_hash,
        status="embedded",
        embedding_file=str(out_path),
        dimensions=actual_dimensions,
        token_count=total_tokens,
        chunk_count=len(chunk_records),
    )


def run_graphify_embedding_manifest(
    *,
    manifest_path: str | Path,
    derived_root: str | Path | None = None,
    max_files: int = DEFAULT_MAX_FILES_PER_RUN,
    dimensions: int = DEFAULT_HASHING_DIMENSIONS,
    max_chars_per_file: int = DEFAULT_MAX_CHARS_PER_FILE,
    max_chars_per_chunk: int = DEFAULT_MAX_CHARS_PER_CHUNK,
    chunk_overlap: int = DEFAULT_CHUNK_OVERLAP,
    provider: str = "ollama",
    allow_smoke_provider: bool = False,
    ollama_base_url: str = DEFAULT_OLLAMA_BASE_URL,
    ollama_model: str = DEFAULT_OLLAMA_MODEL,
    ollama_timeout_seconds: int = DEFAULT_OLLAMA_TIMEOUT_SECONDS,
    resource_preflight: bool = True,
    min_available_mb: int = 1024,
    max_swap_used_mb: int = 512,
    max_load_per_cpu: float = 1.25,
    max_swap_io_pages_per_sec: int = 20,
    unload_ollama_after_run: bool = True,
) -> GraphifyEmbeddingRunReport:
    """Run bounded local embeddings from a Graphify-derived manifest only."""
    if max_files < 1 or max_files > MAX_FILES_PER_RUN_HARD_CAP:
        raise GuardrailError(f"max_files must be between 1 and {MAX_FILES_PER_RUN_HARD_CAP}")
    if max_chars_per_file < 100 or max_chars_per_file > 1_000_000:
        raise GuardrailError("max_chars_per_file must be between 100 and 1000000")
    if max_chars_per_chunk < 200 or max_chars_per_chunk > 20_000:
        raise GuardrailError("max_chars_per_chunk must be between 200 and 20000")
    if chunk_overlap < 0 or chunk_overlap >= max_chars_per_chunk // 2:
        raise GuardrailError("chunk_overlap must be >= 0 and smaller than half max_chars_per_chunk")
    if ollama_timeout_seconds < 1 or ollama_timeout_seconds > 3600:
        raise GuardrailError("ollama_timeout_seconds must be between 1 and 3600")
    if provider not in {"ollama", "local-hashing-v1"}:
        raise GuardrailError(f"Unsupported embedding provider: {provider}")
    if provider == "local-hashing-v1" and not allow_smoke_provider:
        raise GuardrailError("local-hashing-v1 is a smoke/test provider; pass allow_smoke_provider=True for smoke runs")
    normalized_ollama_url = normalize_loopback_ollama_base_url(ollama_base_url) if provider == "ollama" else ollama_base_url
    if provider == "ollama" and ollama_model not in ALLOWED_OLLAMA_MODELS:
        raise GuardrailError(f"Ollama embedding model must be bge-m3 for this runner: {ollama_model!r}")
    payload = _load_manifest(manifest_path)
    sandbox = _safe_sandbox_from_manifest(payload)
    derived_raw = derived_root or payload.get("derived_root") or DEFAULT_GRAPHIFY_EMBEDDING_DERIVED_ROOT
    derived = _safe_derived_root(derived_raw)
    derived.mkdir(parents=True, exist_ok=True)

    candidates = payload.get("candidates")
    if not isinstance(candidates, list):
        raise GuardrailError("Manifest is missing candidates list")
    for item in candidates[:max_files]:
        if not isinstance(item, dict) or not isinstance(item.get("path"), str) or not isinstance(item.get("hash"), str):
            raise GuardrailError("Manifest candidate must include path and hash")
        _candidate_path(sandbox, item["path"])

    resource_report = None
    if provider == "ollama" and resource_preflight:
        resource_report = collect_resource_preflight(
            min_available_mb=min_available_mb,
            max_swap_used_mb=max_swap_used_mb,
            max_load_per_cpu=max_load_per_cpu,
            max_swap_io_pages_per_sec=max_swap_io_pages_per_sec,
        ).to_dict()

    records: list[EmbeddedFileRecord] = []
    ollama_unloaded_after_run: bool | None = None
    try:
        for item in candidates[:max_files]:
            if not isinstance(item, dict) or not isinstance(item.get("path"), str) or not isinstance(item.get("hash"), str):
                raise GuardrailError("Manifest candidate must include path and hash")
            rel_path = item["path"]
            target = _candidate_path(sandbox, rel_path)
            records.append(
                _write_embedding_record(
                    target_file=target,
                    rel_path=rel_path,
                    expected_hash=item["hash"],
                    derived_root=derived,
                    dimensions=dimensions,
                    max_chars_per_file=max_chars_per_file,
                    max_chars_per_chunk=max_chars_per_chunk,
                    chunk_overlap=chunk_overlap,
                    provider=provider,
                    ollama_base_url=normalized_ollama_url,
                    ollama_model=ollama_model,
                    ollama_timeout_seconds=ollama_timeout_seconds,
                )
            )
    finally:
        if provider == "ollama" and unload_ollama_after_run:
            ollama_unloaded_after_run = _ollama_unload(
                base_url=normalized_ollama_url,
                model=ollama_model,
                timeout_seconds=min(max(ollama_timeout_seconds, 5), 60),
            )

    processed = sum(1 for item in records if item.status == "embedded")
    skipped = len(records) - processed
    checkpoint = derived / "checkpoint.json"
    report = GraphifyEmbeddingRunReport(
        mode="graphify-manifest-bounded-embedding-run",
        manifest=str(_require_not_live(manifest_path)),
        derived_root=str(derived),
        provider=provider,
        dimensions=next((item.dimensions for item in records if item.status == "embedded"), dimensions),
        processed=processed,
        skipped=skipped,
        records=records,
        safety={
            "manifest_only": True,
            "live_vault_refused": True,
            "sandbox_required": True,
            "concurrency_one": True,
            "writes_derived_cache_only": True,
            "ollama_loopback_only": provider != "ollama" or normalized_ollama_url in {"http://localhost:11434", "http://127.0.0.1:11434"},
            "semantic_quality": provider == "ollama",
            "live_mutation": False,
            "resource_preflight": resource_report is not None or provider != "ollama",
            "ollama_unload_requested": provider != "ollama" or bool(ollama_unloaded_after_run),
        },
        resource_preflight=resource_report,
        ollama_unloaded_after_run=ollama_unloaded_after_run,
    )
    write_json(checkpoint, {"updated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), **report.to_dict()})
    return report


def embedding_run_to_markdown(report: GraphifyEmbeddingRunReport) -> str:
    lines = [
        "# Graphify-derived bounded embedding run",
        "",
        f"Provider: `{report.provider}`",
        f"Processed: {report.processed}",
        f"Skipped: {report.skipped}",
        "",
        "## Records",
        "",
        "| path | status | chunks | tokens | embedding file | skipped reason |",
        "|---|---|---:|---:|---|---|",
    ]
    for item in report.records:
        lines.append(
            f"| `{item.path}` | {item.status} | {item.chunk_count} | {item.token_count} | "
            f"`{item.embedding_file or ''}` | {item.skipped_reason or ''} |"
        )
    lines.extend(["", "## Safety", ""])
    for key, value in report.safety.items():
        lines.append(f"- {key}: {value}")
    if report.resource_preflight:
        lines.extend(["", "## Resource preflight", ""])
        for key, value in report.resource_preflight.items():
            lines.append(f"- {key}: `{value}`")
    if report.ollama_unloaded_after_run is not None:
        lines.extend(["", "## Ollama lifecycle", "", f"- unloaded_after_run: `{report.ollama_unloaded_after_run}`"])
    lines.append("")
    return "\n".join(lines)


def write_graphify_embedding_run_report(
    *,
    manifest_path: str | Path,
    out_dir: str | Path,
    derived_root: str | Path | None = None,
    max_files: int = DEFAULT_MAX_FILES_PER_RUN,
    dimensions: int = DEFAULT_HASHING_DIMENSIONS,
    max_chars_per_file: int = DEFAULT_MAX_CHARS_PER_FILE,
    max_chars_per_chunk: int = DEFAULT_MAX_CHARS_PER_CHUNK,
    chunk_overlap: int = DEFAULT_CHUNK_OVERLAP,
    provider: str = "ollama",
    allow_smoke_provider: bool = False,
    ollama_base_url: str = DEFAULT_OLLAMA_BASE_URL,
    ollama_model: str = DEFAULT_OLLAMA_MODEL,
    ollama_timeout_seconds: int = DEFAULT_OLLAMA_TIMEOUT_SECONDS,
    resource_preflight: bool = True,
    min_available_mb: int = 1024,
    max_swap_used_mb: int = 512,
    max_load_per_cpu: float = 1.25,
    max_swap_io_pages_per_sec: int = 20,
    unload_ollama_after_run: bool = True,
) -> dict[str, str]:
    report_dir = _require_not_live(out_dir)
    allowed = Path(__file__).resolve().parents[2] / "out" / "reports" / "graphify-embedding-runs"
    if not _is_relative_to(report_dir, allowed.resolve()):
        raise GuardrailError(f"Embedding run report dir must live under {allowed}: {report_dir}")
    report_dir.mkdir(parents=True, exist_ok=True)
    report = run_graphify_embedding_manifest(
        manifest_path=manifest_path,
        derived_root=derived_root,
        max_files=max_files,
        dimensions=dimensions,
        max_chars_per_file=max_chars_per_file,
        max_chars_per_chunk=max_chars_per_chunk,
        chunk_overlap=chunk_overlap,
        provider=provider,
        allow_smoke_provider=allow_smoke_provider,
        ollama_base_url=ollama_base_url,
        ollama_model=ollama_model,
        ollama_timeout_seconds=ollama_timeout_seconds,
        resource_preflight=resource_preflight,
        min_available_mb=min_available_mb,
        max_swap_used_mb=max_swap_used_mb,
        max_load_per_cpu=max_load_per_cpu,
        max_swap_io_pages_per_sec=max_swap_io_pages_per_sec,
        unload_ollama_after_run=unload_ollama_after_run,
    )
    json_path = report_dir / "embedding-run.json"
    md_path = report_dir / "REPORT.md"
    write_json(json_path, report.to_dict())
    md_path.write_text(embedding_run_to_markdown(report), encoding="utf-8")
    return {
        "status": "ok",
        "report": str(md_path),
        "json": str(json_path),
        "processed": str(report.processed),
        "skipped": str(report.skipped),
    }
