from __future__ import annotations

import json
import shutil
import subprocess
import sys
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import pytest

import obslayer.graphify_embedding_runner as runner
from obslayer import GuardrailError, run_graphify_embedding_manifest, write_graphify_embedding_handoff


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def make_manifest(tmp_path: Path) -> tuple[Path, Path]:
    repo = repo_root()
    sandbox = repo / "out" / "sandbox-vaults" / f"runner-{tmp_path.name}"
    if sandbox.exists():
        shutil.rmtree(sandbox)
    (sandbox / "Notes").mkdir(parents=True)
    (sandbox / "Notes" / "Alpha.md").write_text("# Alpha\nSafety apply graph graph\n", encoding="utf-8")
    (sandbox / "Notes" / "Beta.md").write_text("# Beta\nBackup verify graph\n", encoding="utf-8")
    graph_dir = repo / "out" / "reports" / "graphify-embedding-handoff" / f"runner-{tmp_path.name}" / "graphify-out"
    graph_dir.mkdir(parents=True, exist_ok=True)
    graph = {
        "directed": True,
        "multigraph": False,
        "graph": {},
        "nodes": [
            {"id": "a", "source_file": "Notes/Alpha.md", "community": 1},
            {"id": "b", "source_file": "Notes/Beta.md", "community": 1},
        ],
        "links": [{"source": "a", "target": "b"}],
        "hyperedges": [],
        "built_at_commit": "test",
    }
    graph_path = graph_dir / "graph.json"
    graph_path.write_text(json.dumps(graph), encoding="utf-8")
    out = repo / "out" / "reports" / "graphify-embedding-handoff" / f"runner-{tmp_path.name}" / "handoff"
    result = write_graphify_embedding_handoff(
        graph_json=graph_path,
        sandbox_vault=sandbox,
        out_dir=out,
        derived_root=repo / "out" / "external-indexing-spike" / "graphify-derived" / f"runner-{tmp_path.name}",
        max_candidates=10,
    )
    return Path(result["manifest"]), sandbox


def test_runner_embeds_manifest_candidates_only(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    derived = repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"run-{tmp_path.name}"

    report = run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=derived,
        max_files=1,
        dimensions=32,
        provider="local-hashing-v1",
        allow_smoke_provider=True,
    )

    assert report.mode == "graphify-manifest-bounded-embedding-run"
    assert report.provider == "local-hashing-v1"
    assert report.processed == 1
    assert report.skipped == 0
    assert report.safety["manifest_only"] is True
    first = report.records[0]
    assert first.status == "embedded"
    assert first.embedding_file is not None
    embedding = json.loads(Path(first.embedding_file).read_text(encoding="utf-8"))
    assert embedding["provider"] == "local-hashing-v1"
    assert embedding["chunk_count"] >= 1
    assert len(embedding["chunks"][0]["vector"]) == 32
    assert (derived / "checkpoint.json").is_file()


def test_runner_skips_stale_hash(tmp_path: Path) -> None:
    manifest, sandbox = make_manifest(tmp_path)
    (sandbox / "Notes" / "Alpha.md").write_text("changed after graphify\n", encoding="utf-8")

    report = run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"stale-{tmp_path.name}",
        max_files=1,
        dimensions=32,
        provider="local-hashing-v1",
        allow_smoke_provider=True,
    )

    assert report.processed == 0
    assert report.skipped == 1
    assert report.records[0].skipped_reason == "hash_mismatch_manifest_stale"


def test_runner_rejects_non_manifest_path(tmp_path: Path) -> None:
    bad = tmp_path / "embedding-manifest.json"
    bad.write_text(json.dumps({"mode": "graphify-derived-embedding-manifest"}), encoding="utf-8")
    with pytest.raises(GuardrailError, match="generated by graphify_embedding_handoff"):
        run_graphify_embedding_manifest(manifest_path=bad, resource_preflight=False)


def test_runner_cli_writes_report(tmp_path: Path) -> None:
    repo = repo_root()
    manifest, _sandbox = make_manifest(tmp_path)
    out_dir = repo / "out" / "reports" / "graphify-embedding-runs" / f"cli-{tmp_path.name}"
    derived = repo / "out" / "external-indexing-spike" / "graphify-derived" / f"cli-run-{tmp_path.name}"

    completed = subprocess.run(
        [
            sys.executable,
            str(repo / "tools" / "obsidian_graphify_embedding_run.py"),
            "--manifest",
            str(manifest),
            "--out-dir",
            str(out_dir),
            "--derived-root",
            str(derived),
            "--max-files",
            "2",
            "--dimensions",
            "32",
            "--provider",
            "local-hashing-v1",
            "--allow-smoke-provider",
        ],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr + completed.stdout
    payload = json.loads(completed.stdout)
    assert payload["status"] == "ok"
    assert payload["processed"] == "2"
    assert Path(payload["json"]).is_file()
    assert Path(payload["report"]).is_file()


class FakeOllamaHandler(BaseHTTPRequestHandler):
    requests_seen: list[dict[str, object]] = []

    def do_POST(self) -> None:  # noqa: N802
        length = int(self.headers.get("Content-Length", "0"))
        payload = json.loads(self.rfile.read(length).decode("utf-8"))
        FakeOllamaHandler.requests_seen.append(payload)
        text = str(payload.get("input", ""))
        vector = [float(len(text)), 1.0, 0.5]
        body = json.dumps({"embeddings": [vector]}).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, _format: str, *_args: object) -> None:
        return


def test_runner_ollama_provider_uses_small_chunks(tmp_path: Path) -> None:
    FakeOllamaHandler.requests_seen = []
    try:
        server = HTTPServer(("127.0.0.1", 11434), FakeOllamaHandler)
    except OSError as exc:
        pytest.skip(f"loopback Ollama port 11434 unavailable for fake server: {exc}")
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        manifest, _sandbox = make_manifest(tmp_path)
        derived = repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"ollama-{tmp_path.name}"
        if derived.exists():
            shutil.rmtree(derived)
        report = run_graphify_embedding_manifest(
            manifest_path=manifest,
            derived_root=derived,
            max_files=1,
            provider="ollama",
            resource_preflight=False,
            ollama_base_url="http://127.0.0.1:11434",
            ollama_model="bge-m3",
            max_chars_per_chunk=200,
            chunk_overlap=20,
        )
    finally:
        server.shutdown()
        server.server_close()

    assert report.provider == "ollama"
    assert report.processed == 1
    assert report.records[0].dimensions == 3
    assert report.records[0].chunk_count >= 1
    assert FakeOllamaHandler.requests_seen
    assert all(request["model"] == "bge-m3" for request in FakeOllamaHandler.requests_seen)
    assert all(len(str(request["input"])) <= 200 for request in FakeOllamaHandler.requests_seen)


def test_ollama_runner_requests_unload_after_run(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    from obslayer import graphify_embedding_runner as runner

    calls: list[tuple[str, object | None]] = []

    def fake_ollama_embed(text: str, **kwargs: object) -> tuple[list[float], int]:
        calls.append((text, kwargs.get("keep_alive")))
        return [0.1, 0.2, 0.3], len(str(text).split())

    monkeypatch.setattr(runner, "_ollama_embed", fake_ollama_embed)
    derived = repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"unload-{tmp_path.name}"
    if derived.exists():
        shutil.rmtree(derived)

    report = runner.run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=derived,
        max_files=1,
        provider="ollama",
        resource_preflight=False,
        ollama_base_url="http://127.0.0.1:11434",
        ollama_model="bge-m3",
        max_chars_per_chunk=200,
        chunk_overlap=20,
    )

    assert report.ollama_unloaded_after_run is True
    assert report.safety["ollama_unload_requested"] is True
    assert calls[-1][1] == 0
    assert any(keep_alive is None for _text, keep_alive in calls[:-1])


def test_rejects_smoke_provider_without_explicit_gate(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    with pytest.raises(GuardrailError, match="smoke/test provider"):
        run_graphify_embedding_manifest(
            manifest_path=manifest,
            provider="local-hashing-v1",
        )


def test_rejects_non_bge_m3_ollama_model(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    with pytest.raises(GuardrailError, match="bge-m3"):
        run_graphify_embedding_manifest(
            manifest_path=manifest,
            provider="ollama",
            resource_preflight=False,
            ollama_model="not-bge",
            max_files=1,
        )


def test_chunk_text_rejects_too_high_overlap() -> None:
    from obslayer.graphify_embedding_runner import _chunk_text

    with pytest.raises(GuardrailError, match="half"):
        _chunk_text("alpha beta gamma" * 100, max_chars=200, overlap=150)


def test_ollama_adaptive_split_on_large_chunk(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    manifest, sandbox = make_manifest(tmp_path)
    (sandbox / "Notes" / "Alpha.md").write_text("alpha " * 900, encoding="utf-8")
    # Rebuild manifest so the hash matches the larger file.
    manifest, _sandbox = make_manifest(tmp_path)
    (sandbox / "Notes" / "Alpha.md").write_text("alpha " * 900, encoding="utf-8")
    manifest_payload = json.loads(manifest.read_text(encoding="utf-8"))
    import hashlib

    alpha = sandbox / "Notes" / "Alpha.md"
    for item in manifest_payload["candidates"]:
        if item["path"] == "Notes/Alpha.md":
            item["hash"] = "sha256:" + hashlib.sha256(alpha.read_bytes()).hexdigest()
    manifest.write_text(json.dumps(manifest_payload), encoding="utf-8")

    from obslayer import graphify_embedding_runner as runner

    calls: list[int] = []

    def fake_ollama_embed(text: str, **_kwargs: object) -> tuple[list[float], int]:
        calls.append(len(text))
        if len(text) > 1200:
            raise GuardrailError("Local Ollama embedding request failed: HTTP 400: input too large")
        return [0.1, 0.2, 0.3], len(text.split())

    monkeypatch.setattr(runner, "_ollama_embed", fake_ollama_embed)
    derived = repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"adaptive-{tmp_path.name}"
    if derived.exists():
        shutil.rmtree(derived)
    report = runner.run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=derived,
        max_files=1,
        provider="ollama",
        resource_preflight=False,
        max_chars_per_chunk=6000,
        chunk_overlap=200,
    )

    assert report.processed == 1
    assert report.records[0].chunk_count > 1
    assert max(calls) > 1200
    assert all(record.dimensions == 3 for record in report.records)

def test_runner_rejects_tampered_manifest_policy(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    payload["embedding_policy"]["derived_cache_only"] = False
    manifest.write_text(json.dumps(payload), encoding="utf-8")

    with pytest.raises(GuardrailError, match="derived_cache_only"):
        run_graphify_embedding_manifest(manifest_path=manifest, resource_preflight=False)


def test_runner_rejects_non_loopback_ollama_url(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    with pytest.raises(GuardrailError):
        run_graphify_embedding_manifest(
            manifest_path=manifest,
            provider="ollama",
            ollama_base_url="http://example.com:11434",
            max_files=1,
        )


def test_runner_rejects_candidate_path_escape(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    payload["candidates"][0]["path"] = "../escape.md"
    manifest.write_text(json.dumps(payload), encoding="utf-8")

    with pytest.raises(GuardrailError, match="Unsafe manifest candidate path"):
        run_graphify_embedding_manifest(manifest_path=manifest, resource_preflight=False)


def test_runner_rejects_protected_candidate_path(tmp_path: Path) -> None:
    manifest, sandbox = make_manifest(tmp_path)
    protected = sandbox / ".obsidian" / "secret.md"
    protected.parent.mkdir(parents=True, exist_ok=True)
    protected.write_text("secret", encoding="utf-8")
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    payload["candidates"][0]["path"] = ".obsidian/secret.md"
    payload["candidates"][0]["hash"] = "sha256:" + __import__("hashlib").sha256(protected.read_bytes()).hexdigest()
    manifest.write_text(json.dumps(payload), encoding="utf-8")

    with pytest.raises(GuardrailError, match="Unsafe manifest candidate path"):
        run_graphify_embedding_manifest(manifest_path=manifest, resource_preflight=False)


def test_runner_rejects_derived_root_escape(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    with pytest.raises(GuardrailError, match="derived root"):
        run_graphify_embedding_manifest(
            manifest_path=manifest,
            derived_root=tmp_path / "outside-derived",
            provider="local-hashing-v1",
            allow_smoke_provider=True,
        )


def test_runner_reuses_existing_embedding_checkpoint(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    derived = repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"resume-{tmp_path.name}"
    first = run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=derived,
        max_files=1,
        provider="local-hashing-v1",
        allow_smoke_provider=True,
        dimensions=32,
    )
    assert first.processed == 1

    from obslayer import graphify_embedding_runner as runner

    def fail_hashing(*_args: object, **_kwargs: object) -> tuple[list[float], int]:
        raise AssertionError("resume should reuse the existing embedding file")

    monkeypatch.setattr(runner, "_hashing_embedding", fail_hashing)
    second = runner.run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=derived,
        max_files=1,
        provider="local-hashing-v1",
        allow_smoke_provider=True,
        dimensions=32,
    )
    assert second.processed == 1
    assert second.records[0].embedding_file == first.records[0].embedding_file

def test_runner_rejects_report_dir_escape(tmp_path: Path) -> None:
    from obslayer.graphify_embedding_runner import write_graphify_embedding_run_report

    manifest, _sandbox = make_manifest(tmp_path)
    with pytest.raises(GuardrailError, match="report dir"):
        write_graphify_embedding_run_report(
            manifest_path=manifest,
            out_dir=tmp_path / "outside-report",
            provider="local-hashing-v1",
            allow_smoke_provider=True,
        )



def test_runner_ollama_timeout_forwarded(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    from obslayer import graphify_embedding_runner as runner

    seen: list[tuple[int, object | None]] = []

    def fake_ollama_embed(text: str, **kwargs: object) -> tuple[list[float], int]:
        seen.append((int(kwargs.get("timeout_seconds", -1)), kwargs.get("keep_alive")))
        return [0.1, 0.2, 0.3], len(text.split())

    monkeypatch.setattr(runner, "_ollama_embed", fake_ollama_embed)
    derived = repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"timeout-{tmp_path.name}"
    if derived.exists():
        shutil.rmtree(derived)
    report = runner.run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=derived,
        max_files=1,
        provider="ollama",
        resource_preflight=False,
        ollama_timeout_seconds=321,
        max_chars_per_chunk=200,
        chunk_overlap=20,
    )

    assert report.processed == 1
    embedding_timeouts = [timeout for timeout, keep_alive in seen if keep_alive is None]
    assert embedding_timeouts and all(value == 321 for value in embedding_timeouts)
    assert seen[-1][1] == 0


def test_runner_ollama_preflight_is_fail_closed(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    from obslayer import graphify_embedding_runner as runner

    def fail_preflight(**_kwargs: object) -> object:
        raise GuardrailError("Resource preflight failed: SwapUsed 1500MB > 512MB")

    monkeypatch.setattr(runner, "collect_resource_preflight", fail_preflight)

    with pytest.raises(GuardrailError, match="Resource preflight failed"):
        runner.run_graphify_embedding_manifest(
            manifest_path=manifest,
            provider="ollama",
            max_files=1,
        )


def test_runner_can_skip_preflight_for_isolated_ollama_unit_test(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    from obslayer import graphify_embedding_runner as runner

    def fail_preflight(**_kwargs: object) -> object:
        raise GuardrailError("Resource preflight failed")

    monkeypatch.setattr(runner, "collect_resource_preflight", fail_preflight)
    monkeypatch.setattr(runner, "_ollama_embed", lambda text, **_kwargs: ([0.1, 0.2, 0.3], len(text.split())))

    report = runner.run_graphify_embedding_manifest(
        manifest_path=manifest,
        derived_root=repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"skip-preflight-{tmp_path.name}",
        provider="ollama",
        max_files=1,
        resource_preflight=False,
    )

    assert report.processed == 1
    assert report.resource_preflight is None
    assert report.safety["resource_preflight"] is False

def test_empty_file_is_skipped_without_calling_ollama(tmp_path, monkeypatch):
    sandbox = tmp_path / "sandbox"
    sandbox.mkdir()
    target = sandbox / "empty.md"
    target.write_text("", encoding="utf-8")
    derived = tmp_path / "derived"

    def fail_embed(*args, **kwargs):
        raise AssertionError("empty files must not call Ollama")

    monkeypatch.setattr(runner, "_ollama_embed", fail_embed)
    record = runner._write_embedding_record(
        target_file=target,
        rel_path="empty.md",
        expected_hash=runner._sha256(target),
        derived_root=derived,
        dimensions=128,
        max_chars_per_file=5000,
        max_chars_per_chunk=500,
        chunk_overlap=50,
        provider="ollama",
        ollama_base_url="http://localhost:11434",
        ollama_model="bge-m3",
        ollama_timeout_seconds=5,
    )

    assert record.status == "skipped"
    assert record.skipped_reason == "empty_text_after_truncation"
    assert record.embedding_file is None
    assert not (derived / "embeddings").exists()




def test_embedding_query_smoke_searches_existing_run(tmp_path: Path) -> None:
    manifest, _sandbox = make_manifest(tmp_path)
    derived = repo_root() / "out" / "external-indexing-spike" / "graphify-derived" / f"query-{tmp_path.name}"
    if derived.exists():
        shutil.rmtree(derived)
    run_out = repo_root() / "out" / "reports" / "graphify-embedding-runs" / f"query-{tmp_path.name}"
    from obslayer import write_graphify_embedding_run_report

    write_graphify_embedding_run_report(
        manifest_path=manifest,
        out_dir=run_out,
        derived_root=derived,
        max_files=2,
        dimensions=32,
        provider="local-hashing-v1",
        allow_smoke_provider=True,
    )

    from obslayer.graphify_embedding_query import run_graphify_embedding_query_smoke

    report = run_graphify_embedding_query_smoke(
        run_json=run_out / "embedding-run.json",
        queries=["safety graph"],
        provider="local-hashing-v1",
        dimensions=32,
    )

    assert report.mode == "graphify-embedding-query-smoke"
    assert report.records == 2
    assert report.embedded_files == 2
    assert report.chunks_indexed >= 2
    assert report.missing_embedding_files == []
    assert report.queries[0].hits
    assert report.safety["derived_cache_only"] is True
    assert report.safety["live_mutation"] is False


def test_embedding_query_cli_writes_report(tmp_path: Path) -> None:
    repo = repo_root()
    manifest, _sandbox = make_manifest(tmp_path)
    derived = repo / "out" / "external-indexing-spike" / "graphify-derived" / f"query-cli-{tmp_path.name}"
    run_out = repo / "out" / "reports" / "graphify-embedding-runs" / f"query-cli-{tmp_path.name}"
    from obslayer import write_graphify_embedding_run_report

    write_graphify_embedding_run_report(
        manifest_path=manifest,
        out_dir=run_out,
        derived_root=derived,
        max_files=2,
        dimensions=32,
        provider="local-hashing-v1",
        allow_smoke_provider=True,
    )
    query_out = repo / "out" / "reports" / "graphify-embedding-query-smoke" / f"cli-{tmp_path.name}"
    completed = subprocess.run(
        [
            sys.executable,
            str(repo / "tools" / "obsidian_graphify_embedding_query.py"),
            "--run-json",
            str(run_out / "embedding-run.json"),
            "--out-dir",
            str(query_out),
            "--query",
            "backup verify graph",
            "--provider",
            "local-hashing-v1",
            "--dimensions",
            "32",
        ],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr + completed.stdout
    payload = json.loads(completed.stdout)
    assert payload["status"] == "ok"
    assert int(payload["chunks_indexed"]) >= 2
    assert Path(payload["json"]).is_file()
    assert Path(payload["report"]).is_file()


def test_embedding_query_rejects_outside_run_json(tmp_path: Path) -> None:
    bad = tmp_path / "embedding-run.json"
    bad.write_text(json.dumps({"records": [], "derived_root": str(tmp_path)}), encoding="utf-8")
    from obslayer.graphify_embedding_query import run_graphify_embedding_query_smoke

    with pytest.raises(GuardrailError, match="Embedding query run json"):
        run_graphify_embedding_query_smoke(run_json=bad, queries=["x"], provider="local-hashing-v1")
