name: renovate

on:
  schedule:
    - cron: '17 4 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read

jobs:
  renovate:
    name: renovate / dependency updates
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Renovate
        uses: renovatebot/github-action@13f127373fd3dc43b41b0979e37ba570d6c2b8f4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
